/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'primary':                   '#004782',
        'on-primary':                '#ffffff',
        'primary-container':         '#185fa5',
        'on-primary-container':      '#c1d9ff',
        'secondary':                 '#4c5f7c',
        'on-secondary':              '#ffffff',
        'secondary-container':       '#c7dbfd',
        'on-secondary-container':    '#4c607d',
        'tertiary':                  '#6f3800',
        'on-tertiary':               '#ffffff',
        'tertiary-container':        '#924b00',
        'on-tertiary-container':     '#ffceac',
        'error':                     '#ba1a1a',
        'on-error':                  '#ffffff',
        'error-container':           '#ffdad6',
        'on-error-container':        '#93000a',
        'background':                '#f9f9f7',
        'on-background':             '#1a1c1b',
        'surface':                   '#f9f9f7',
        'on-surface':                '#1a1c1b',
        'surface-variant':           '#e2e3e1',
        'on-surface-variant':        '#424751',
        'outline':                   '#727782',
        'outline-variant':           '#c2c6d2',
        'inverse-surface':           '#2f3130',
        'inverse-on-surface':        '#f1f1ef',
        'inverse-primary':           '#a4c9ff',
        'surface-container-lowest':  '#ffffff',
        'surface-container-low':     '#f4f4f2',
        'surface-container':         '#eeeeec',
        'surface-container-high':    '#e8e8e6',
        'surface-container-highest': '#e2e3e1',
        'surface-bright':            '#f9f9f7',
        'surface-dim':               '#dadad8',
        'surface-tint':              '#1960a6',
      },
      fontFamily: {
        sans:     ['Inter', 'sans-serif'],
        headline: ['Inter', 'sans-serif'],
        mono:     ['JetBrains Mono', 'monospace'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg:      '0.25rem',
        xl:      '0.5rem',
        full:    '0.75rem',
      },
    },
  },
  plugins: [],
}
